import sys
import socket
from ppsay.feed import Feed

socket.setdefaulttimeout(10.0)

class NewsquestWeekliesFeed(Feed):
    feed_urls = [
        'http://www.tewkesburyadmag.co.uk/news/rss/',
        'http://www.suttonguardian.co.uk/news/rss/',
        'http://www.wandsworthguardian.co.uk/news/rss/',
        'http://www.wallingfordherald.co.uk/news/rss/',
        'http://www.sthelensstar.co.uk/news/rss/',
        'http://www.richmondandtwickenhamtimes.co.uk/news/rss/',
        'http://www.herefordtimes.com/news/rss/',
        'http://www.enfieldindependent.co.uk/news/rss/',
        'http://www.basingstokegazette.co.uk/news/rss/',
        'http://www.bucksfreepress.co.uk/news/rss/',
        'http://www.darlingtonandstocktontimes.co.uk/news/rss/',
        'http://www.haringeyindependent.co.uk/news/rss/',
        'http://www.hampshirechronicle.co.uk/news/rss/',
        'http://www.witneygazette.co.uk/news/rss/',
        'http://www.essexcountystandard.co.uk/news/rss/',
        'http://www.times-series.co.uk/news/rss/',
        'http://www.gazetteseries.co.uk/news/rss/',
        'http://www.bridgwatermercury.co.uk/news/rss/',
        'http://www.middevonstar.co.uk/news/rss/',
        'http://www.kingstonguardian.co.uk/news/rss/',
        'http://www.maldonandburnhamstandard.co.uk/news/rss/',
        'http://www.ilkleygazette.co.uk/news/rss/',
        'http://www.middlewichguardian.co.uk/news/rss/',
        'http://www.freepressseries.co.uk/news/rss/',
        'http://www.stalbansreview.co.uk/news/rss/',
        'http://www.bicesteradvertiser.net/news/rss/',
        'http://www.chorleycitizen.co.uk/news/rss/',
        'http://www.didcotherald.co.uk/news/rss/',
        'http://www.bridportnews.co.uk/news/rss/',
        'http://www.hillingdontimes.co.uk/news/rss/',
        'http://www.burytimes.co.uk/news/rss/',
        'http://www.messengernewspapers.co.uk/news/rss/',
        'http://www.andoveradvertiser.co.uk/news/rss/',
        'http://www.wharfedaleobserver.co.uk/news/rss/',
        'http://www.westerntelegraph.co.uk/news/rss/',
        'http://www.dailyecho.co.uk/news/rss/',
        'http://www.swanageandwarehamadvertiser.co.uk/news/rss/',
        'http://www.tivysideadvertiser.co.uk/news/rss/',
        'http://www.ealingtimes.co.uk/news/rss/',
        'http://www.theadvertiserseries.co.uk/news/rss/',
        'http://www.campaignseries.co.uk/news/rss/',
        'http://www.halesowennews.co.uk/news/rss/',
        'http://www.braintreeandwithamtimes.co.uk/news/rss/',
        'http://www.swindonadvertiser.co.uk/news/rss/',
        'http://www.knutsfordguardian.co.uk/news/rss/',
        'http://www.durhamtimes.co.uk/news/rss/',
        'http://www.cotswoldjournal.co.uk/news/rss/',
        'http://www.alcesterchronicle.co.uk/news/rss/',
        'http://www.wantageherald.co.uk/news/rss/',
        'http://www.redditchadvertiser.co.uk/news/rss/',
        'http://www.eveshamjournal.co.uk/news/rss/',
        'http://www.wirralglobe.co.uk/news/rss/',
        'http://www.harrowtimes.co.uk/news/rss/',
        'http://www.guardian-series.co.uk/news/rss/',
        'http://www.barryanddistrictnews.co.uk/news/rss/',
        'http://www.thurrockgazette.co.uk/news/rss/',
        'http://www.stroudnewsandjournal.co.uk/news/rss/',
        'http://www.borehamwoodtimes.co.uk/news/rss/',
        'http://www.worcesternews.co.uk/news/rss/',
        'http://www.cravenherald.co.uk/news/rss/',
        'http://www.wimbledonguardian.co.uk/news/rss/',
        'http://www.falmouthpacket.co.uk/news/rss/',
        'http://www.thewestmorlandgazette.co.uk/news/rss/',
        'http://www.surreycomet.co.uk/news/rss/',
        'http://www.clactonandfrintongazette.co.uk/news/rss/',
        'http://www.theargus.co.uk/leader/news/rss/',
        'http://www.wiltsglosstandard.co.uk/news/rss/',
        'http://www.somersetcountygazette.co.uk/news/rss/',
        'http://www.watfordobserver.co.uk/news/rss/',
        'http://www.croydonguardian.co.uk/news/rss/',
        'http://www.asianimage.co.uk/news/rss/',
        'http://www.truropacket.co.uk/news/rss/',
        'http://www.chardandilminsternews.co.uk/news/rss/',
        'http://www.thepacket.co.uk/news/rss/',
        'http://www.yeovilexpress.co.uk/news/rss/',
        'http://www.northwichguardian.co.uk/news/rss/',
        'http://www.southendstandard.co.uk/news/rss/',
        'http://www.thetelegraphandargus.co.uk/news/rss/',
        'http://www.gazette-news.co.uk/news/rss/',
        'http://www.kidderminstershuttle.co.uk/news/rss/',
        'http://www.chelmsfordweeklynews.co.uk/news/rss/',
        'http://www.streathamguardian.co.uk/news/rss/',
        'http://www.leighjournal.co.uk/news/rss/',
        'http://www.thisisthewestcountry.co.uk/news/rss/',
        'http://www.newsshopper.co.uk/news/rss/',
        'http://www.penarthtimes.co.uk/news/rss/',
        'http://www.epsomguardian.co.uk/news/rss/',
        'http://www.basildonrecorder.co.uk/news/rss/',
        'http://www.oxfordtimes.co.uk/news/rss/',
        'http://www.droitwichadvertiser.co.uk/news/rss/',
        'http://www.keighleynews.co.uk/news/rss/',
        'http://www.romseyadvertiser.co.uk/news/rss/',
        'http://www.oxfordmail.co.uk/news/rss/',
        'http://www.warringtonguardian.co.uk/news/rss/',
        'http://www.theboltonnews.co.uk/news/rss/',
        'http://www.milfordmercury.co.uk/news/rss/',
        'http://www.redhillandreigatelife.co.uk/news/rss/',
        'http://www.camborneredruthpacket.co.uk/news/rss/',
        'http://www.stourbridgenews.co.uk/news/rss/',
        'http://www.dudleynews.co.uk/news/rss/',
        'http://www.berrowsjournal.co.uk/news/rss/',
        'http://www.bexleynewsshopper.co.uk/news/rss/',
        'http://www.brentwoodweeklynews.co.uk/news/rss/',
        'http://www.banburycake.co.uk/news/rss/',
        'http://www.wiltshiretimes.co.uk/news/rss/',
        'http://www.southwalesargus.co.uk/news/rss/',
        'http://www.blackburncitizen.co.uk/news/rss/',
        'http://www.malverngazette.co.uk/news/rss/',
        'http://www.southwalesguardian.co.uk/news/rss/',
        'http://www.bromsgroveadvertiser.co.uk/news/rss/',
        'http://www.ledburyreporter.co.uk/news/rss/',
        'http://www.thepress.co.uk/news/rss/',
        'http://www.gazetteherald.co.uk/news/rss/',
        'http://www.elmbridgeguardian.co.uk/news/rss/',
        'http://www.burnhamandhighbridgeweeklynews.co.uk/news/rss/',
        'http://www.burnleycitizen.co.uk/news/rss/',
        'http://www.ludlowadvertiser.co.uk/news/rss/',
        'http://www.creweguardian.co.uk/news/rss/',
        'http://www.halsteadgazette.co.uk/news/rss/',
        'http://www.salisburyjournal.co.uk/news/rss/',
        'http://www.abingdonherald.co.uk/news/rss/',
        'http://www.harwichandmanningtreestandard.co.uk/news/rss/',
        'http://www.prestwichandwhitefieldguide.co.uk/news/rss/',
        'http://www.winsfordguardian.co.uk/news/rss/',
    ]

    source = 'rss/newsquest_weeklies'
    match_condition = [(1,0,1),]
 
    def clean_link(self,x):
        return x.split('#')[0].split('?')[0]

if __name__ == "__main__":
    fresh = False
    if len(sys.argv) > 1:
        fresh = (sys.argv[1] == "fresh")

    feed = NewsquestWeekliesFeed(fresh)
    feed.fetch()

